services:
  csvserver:
    image: infracloudio/csvserver:latest 
    ports:
      - "9393:9300"
    volumes:
      - /root/assignment/csvserver/solution/inputFile:/csvserver/inputdata
    environment:
      - CSVSERVER_BORDER=Orange
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
